"""
Load command: assemble config/ source files into a single .env file,
or retrieve a specific file from a deployment.

The generated .env has marked sections that map back to source files
in the config/ directory, enabling round-tripping via the save command.

Structured files (YAML, JSON) can be loaded from a deployment and
optionally deep-merged with a local override layer.
"""

import base64
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import click
import yaml

from .output import error, ok, warn

_FILES_DIR = Path("config/files")
_GITIGNORE_CONTENT = "# Auto-generated by dotconfig — keep decrypted files out of git\n*\n!.gitignore\n"


def _ensure_files_dir() -> Path:
    """Create config/files/ with a .gitignore if it doesn't exist."""
    _FILES_DIR.mkdir(parents=True, exist_ok=True)
    gitignore = _FILES_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE_CONTENT)
    return _FILES_DIR


def _env_lines_to_dict(content: str) -> Dict[str, str]:
    """Parse KEY=VALUE lines into a dict, skipping comments and blanks.

    A leading shell-style ``export `` on assignment lines is stripped so
    that JSON/YAML output uses the canonical variable name as the key.
    Surrounding quotes on values are stripped (both single and double).
    """
    result: Dict[str, str] = {}
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("export "):
            stripped = stripped[len("export "):].lstrip()
        if "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip surrounding quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        result[key] = value
    return result


# ---------------------------------------------------------------------------
# Structured-file helpers (YAML / JSON deep merge)
# ---------------------------------------------------------------------------

_YAML_SUFFIXES = {".yaml", ".yml"}
_JSON_SUFFIXES = {".json"}


def _deep_merge(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    """Recursively merge *override* into a copy of *base*.

    Override values win at the leaf level.  Nested dicts are merged
    recursively; all other types are replaced outright.
    """
    result = dict(base)
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _read_file_content(path: Path, sops_config: Optional[Path]) -> str:
    """Read a file, auto-decrypting if SOPS-encrypted."""
    if _is_sops_encrypted(path):
        content = _decrypt_sops(path, sops_config)
        if content is None:
            error(f"failed to decrypt {path}")
            sys.exit(1)
        return content
    return path.read_text()


def _parse_structured(text: str, suffix: str) -> Dict[str, Any]:
    """Parse text as YAML or JSON based on *suffix*."""
    if suffix in _YAML_SUFFIXES:
        return yaml.safe_load(text) or {}
    if suffix in _JSON_SUFFIXES:
        return json.loads(text)
    error(f"cannot merge files with suffix '{suffix}' — only .yaml, .yml, and .json are supported")
    sys.exit(1)


def _serialize_structured(data: Dict[str, Any], suffix: str) -> str:
    """Serialize a dict back to YAML or JSON."""
    if suffix in _YAML_SUFFIXES:
        return yaml.dump(data, default_flow_style=False, sort_keys=False)
    if suffix in _JSON_SUFFIXES:
        return json.dumps(data, indent=2) + "\n"
    error(f"cannot serialize to suffix '{suffix}'")
    sys.exit(1)


def _is_sops_encrypted(filepath: Path) -> bool:
    """Return True if *filepath* appears to be SOPS-encrypted.

    Detection heuristic: SOPS adds a ``sops`` metadata key to JSON and
    YAML files, and a ``sops_`` prefix to dotenv/ini-style files.  We
    check for the presence of these markers in the raw file content.
    """
    try:
        text = filepath.read_text()
    except OSError:
        return False
    # JSON / YAML: top-level "sops" key written by sops
    if '"sops"' in text or "\nsops:\n" in text or text.startswith("sops:\n"):
        return True
    # dotenv / ini: sops stores metadata as sops_version=, sops_mac=, etc.
    if "sops_version=" in text or "sops_mac=" in text:
        return True
    return False


def _decrypt_sops(filepath: Path, sops_config: Optional[Path] = None) -> Optional[str]:
    """Decrypt a SOPS-encrypted file.

    Returns decrypted content as a string, or None if decryption is
    unavailable (sops not installed, key missing, or file unreadable).

    If *sops_config* is provided and exists, it is passed to sops via
    ``--config`` so that a non-dotfile ``sops.yaml`` inside the config
    directory is found even when it would not be auto-discovered.
    """
    try:
        cmd = ["sops"]
        if sops_config is not None and sops_config.exists():
            cmd += ["--config", str(sops_config)]
        cmd += ["--decrypt", str(filepath)]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout
    except FileNotFoundError:
        warn(f"sops not found — skipping encrypted file {filepath}")
        return None
    except subprocess.CalledProcessError as e:
        warn(f"sops decryption failed for {filepath}: {e.stderr.strip()}")
        return None


def _secrets_companion(filename: str) -> str:
    """Return the secrets companion filename.

    ``app.yaml`` → ``app.secrets.yaml``,
    ``config.json`` → ``config.secrets.json``.
    """
    p = Path(filename)
    return f"{p.stem}.secrets{p.suffix}"


def _load_structured_with_secrets(
    dir_path: Path,
    filename: str,
    suffix: str,
    sops_config: Path,
) -> Optional[Dict[str, Any]]:
    """Load a structured file from *dir_path*, merging its secrets companion.

    Returns the parsed dict with secrets overlaid, or None if the main
    file does not exist.
    """
    main_path = dir_path / filename
    if not main_path.exists():
        return None

    text = _read_file_content(main_path, sops_config)
    data = _parse_structured(text, suffix)

    # Check for secrets companion and merge if present
    companion_name = _secrets_companion(filename)
    companion_path = dir_path / companion_name
    if companion_path.exists():
        sec_text = _read_file_content(companion_path, sops_config)
        sec_data = _parse_structured(sec_text, suffix)
        data = _deep_merge(data, sec_data)

    return data


def load_file(
    deployment: Optional[str],
    local: Optional[str],
    filename: str,
    config_dir: Path,
    output: Optional[Path],
    to_stdout: bool,
) -> None:
    """Load a single file from a deployment or local directory.

    Resolves the file path(s):
      - With only *deployment*: ``config/{deployment}/{filename}``
      - With only *local*: ``config/local/{local}/{filename}``
      - With both: deep-merges the deployment file (base) with the local
        file (override).  Supported for YAML and JSON only.

    Secrets companion files (e.g. ``app.secrets.yaml``) are automatically
    detected, decrypted, and merged on top of the main file.

    For merge mode the layering order is:
      1. Deploy public file (base)
      2. Deploy secrets companion (overlay)
      3. Local override file (overlay)
      4. Local secrets companion (overlay)

    Writes to *output* (defaulting to ``./{filename}``) or prints to
    stdout when *to_stdout* is True.
    """
    if not deployment and not local:
        error("--deploy or --local is required with --file")
        sys.exit(1)

    sops_config = config_dir / "sops.yaml"
    suffix = Path(filename).suffix.lower()

    if deployment and local:
        # Merge mode: deployment base + local override (4-layer)
        if suffix not in _YAML_SUFFIXES and suffix not in _JSON_SUFFIXES:
            error(f"cannot merge '{suffix}' files — only .yaml, .yml, and .json are supported")
            sys.exit(1)

        deploy_dir = config_dir / deployment
        local_dir = config_dir / "local" / local

        deploy_data = _load_structured_with_secrets(deploy_dir, filename, suffix, sops_config)
        if deploy_data is None:
            error(f"deployment file not found: {deploy_dir / filename}")
            sys.exit(1)

        local_data = _load_structured_with_secrets(local_dir, filename, suffix, sops_config)
        if local_data is not None:
            merged = _deep_merge(deploy_data, local_data)
        else:
            warn(f"local file not found: {local_dir / filename} — using deployment file only")
            merged = deploy_data

        content = _serialize_structured(merged, suffix)

    elif suffix in _YAML_SUFFIXES or suffix in _JSON_SUFFIXES:
        # Single structured file — load with secrets companion
        if local:
            dir_path = config_dir / "local" / local
        else:
            dir_path = config_dir / deployment

        data = _load_structured_with_secrets(dir_path, filename, suffix, sops_config)
        if data is None:
            error(f"file not found: {dir_path / filename}")
            sys.exit(1)

        content = _serialize_structured(data, suffix)

    else:
        # Non-structured file — raw load
        if local:
            source = config_dir / "local" / local / filename
        else:
            source = config_dir / deployment / filename

        if not source.exists():
            error(f"file not found: {source}")
            sys.exit(1)

        content = _read_file_content(source, sops_config)

    if to_stdout:
        click.echo(content, nl=False)
    else:
        if output:
            dest = output
        else:
            files_dir = _ensure_files_dir()
            dest = files_dir / filename
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
        dest.chmod(0o600)
        ok(f"Written to {dest}")


def _to_layer_list(value) -> list:
    """Normalize a deployment/local arg into an ordered list of names.

    Accepts ``None`` (→ ``[]``), a string (→ ``[value]``), or any iterable
    of strings (→ ``list(value)``). Used to keep ``load_config`` and
    ``save_config`` back-compat for the historical
    ``deployment="dev", local="alice"`` calling convention while supporting
    multi-layer ``["dev", "prod"]`` callers from the CLI.
    """
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _read_env_layers(
    deployments: list,
    locals_: list,
    config_dir: Path,
) -> tuple:
    """Read all .env layers (deploy + local) and return them in layer order.

    Returns ``(sops_config, deploy_layers, local_layers)`` where each layer
    list contains tuples of ``(name, public_text, secrets_text)``.
    Missing files contribute empty strings (with a warning for missing
    locals — deployments are required and exit on missing).
    """
    sops_config = config_dir / "sops.yaml"

    deploy_layers: list = []
    for deployment in deployments:
        deploy_env = config_dir / deployment / "public.env"
        if not deploy_env.exists():
            error(f"deployment config file not found: {deploy_env}")
            sys.exit(1)
        public_text = deploy_env.read_text().strip()

        secrets_text = ""
        secrets_env = config_dir / deployment / "secrets.env"
        if secrets_env.exists():
            secrets_text = _read_file_content(secrets_env, sops_config).strip()

        deploy_layers.append((deployment, public_text, secrets_text))

    local_layers: list = []
    for local in locals_:
        local_env = config_dir / "local" / local / "public.env"
        if local_env.exists():
            local_public_text = local_env.read_text().strip()
        else:
            warn(f"local config file not found: {local_env} — public-local section will be empty")
            local_public_text = ""

        local_secrets_text = ""
        secrets_local = config_dir / "local" / local / "secrets.env"
        if secrets_local.exists():
            local_secrets_text = _read_file_content(secrets_local, sops_config).strip()

        local_layers.append((local, local_public_text, local_secrets_text))

    return sops_config, deploy_layers, local_layers


def _split_path(dest: Path) -> Path:
    """Return the ``.secret`` companion path for *dest*.

    ``.env`` → ``.env.secret``, ``.env.json`` → ``.env.secret.json``.
    """
    name = dest.name
    if name.startswith(".env"):
        # .env -> .env.secret, .env.json -> .env.secret.json
        rest = name[4:]  # everything after ".env"
        return dest.with_name(f".env.secret{rest}")
    # fallback: insert .secret before extension
    return dest.with_name(f"{dest.stem}.secret{dest.suffix}")


def _strip_export_prefix(text: str) -> str:
    """Remove leading 'export ' from assignment lines in *text*.

    Blank lines, comment lines, and lines that don't start with 'export '
    are returned unchanged. Leading whitespace before 'export ' is preserved.
    """
    if not text:
        return text
    out_lines = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("export "):
            indent = line[: len(line) - len(stripped)]
            out_lines.append(indent + stripped[len("export "):])
        else:
            out_lines.append(line)
    return "\n".join(out_lines)


def _embed_files_section(
    mappings: tuple,
    deploy_dirs: List[Path],
    sops_config: Path,
) -> List[str]:
    """Load files from deploy dirs, base64-encode, return list of VAR=<base64> lines.

    Searches deploy_dirs in order; first match wins. Auto-decrypts SOPS-encrypted
    files. Returns a list of lines suitable for appending to the .env.
    """
    lines = []
    for mapping in mappings:
        if "=" not in mapping:
            error(f"--embed value must be VAR=filename, got: {mapping}")
            sys.exit(1)
        var_name, _, filename = mapping.partition("=")
        var_name = var_name.strip()
        filename = filename.strip()

        source = None
        for deploy_dir in deploy_dirs:
            candidate = deploy_dir / filename
            if candidate.exists():
                source = candidate
                break

        if source is None:
            error(f"file not found in any deployment: {filename}")
            sys.exit(1)

        if _is_sops_encrypted(source):
            content = _decrypt_sops(source, sops_config)
            if content is None:
                error(f"failed to decrypt {source}")
                sys.exit(1)
            content_bytes = content.encode()
        else:
            content_bytes = source.read_bytes()

        b64 = base64.b64encode(content_bytes).decode()
        lines.append(f"{var_name}={b64}")

    return lines


def load_config(
    deployment,
    local,
    config_dir: Path,
    output: Optional[Path],
    to_stdout: bool = False,
    fmt: str = "env",
    flat: bool = False,
    split: bool = False,
    embed_files: tuple = (),
    no_export: bool = False,
) -> None:
    """Assemble config source files into a single .env, JSON, or YAML file.

    *deployment* and *local* may be strings (single layer, legacy form),
    lists of strings (multi-layer stacks), or ``None`` / ``[]``.  Layers
    are applied in order — within deployments first, then within locals,
    last-write-wins.

    Reads from, for each layer:
      - config/{deployment}/public.env            (public deployment config)
      - config/{deployment}/secrets.env           (SOPS-encrypted secrets)
      - config/local/{local}/public.env           (public local overrides, optional)
      - config/local/{local}/secrets.env          (encrypted local secrets, optional)

    When *fmt* is ``"env"`` (default), writes a .env with marked sections
    that enable round-tripping via the save command.  Single-layer
    invocations write the legacy ``# CONFIG_DEPLOY=`` / ``# CONFIG_LOCAL=``
    metadata keys for byte-for-byte parity with previous releases;
    multi-layer invocations write ``# CONFIG_DEPLOYS=<csv>`` /
    ``# CONFIG_LOCALS=<csv>``.

    When *fmt* is ``"json"`` or ``"yaml"``, writes a structured file with
    top-level keys for each deployment/local name and ``public``/``secrets``
    sub-keys.  A ``_dotconfig`` metadata key records the deployment and
    local names for round-tripping.  Multi-layer stacks with structured
    output are not supported in this iteration; the CLI raises a usage
    error before reaching this code.

    When *flat* is True (requires ``"json"`` or ``"yaml"``), all layers are
    merged into a single flat dict (last-write-wins).

    When *split* is True, public values are written to the main output file
    and secret values are written to a ``.secret`` companion file
    (e.g. ``.env`` + ``.env.secret``).

    Default output filenames: ``.env``, ``.env.json``, or ``.env.yaml``.

    When *to_stdout* is True the assembled content is printed to stdout
    instead of being written to a file.
    """
    deployments = _to_layer_list(deployment)
    locals_ = _to_layer_list(local)

    if not deployments:
        error("at least one deployment is required")
        sys.exit(1)

    _, deploy_layers, local_layers = _read_env_layers(deployments, locals_, config_dir)

    # ---- Single-layer view used by structured (json/yaml) and split paths.
    # Both legacy code paths only handle one deployment + one local; the CLI
    # raises a UsageError before reaching here when stacks are passed
    # alongside --json/--yaml/--split.
    public_text = deploy_layers[0][1] if deploy_layers else ""
    secrets_text = deploy_layers[0][2] if deploy_layers else ""
    local_public_text = local_layers[0][1] if local_layers else ""
    local_secrets_text = local_layers[0][2] if local_layers else ""
    deployment_first = deployments[0]
    local_first = locals_[0] if locals_ else None

    if split:
        # ---- Split mode: public file + secret companion ----
        if fmt in ("json", "yaml"):
            public_dict = _env_lines_to_dict(public_text)
            secrets_dict = _env_lines_to_dict(secrets_text)
            local_public_dict = _env_lines_to_dict(local_public_text)
            local_secrets_dict = _env_lines_to_dict(local_secrets_text)

            public_merged: Dict[str, str] = {}
            public_merged.update(public_dict)
            public_merged.update(local_public_dict)

            secrets_merged: Dict[str, str] = {}
            secrets_merged.update(secrets_dict)
            secrets_merged.update(local_secrets_dict)

            serialize = json.dumps if fmt == "json" else yaml.dump
            if fmt == "json":
                public_assembled = json.dumps(public_merged, indent=2) + "\n"
                secrets_assembled = json.dumps(secrets_merged, indent=2) + "\n"
                default_output = Path(".env.json")
            else:
                public_assembled = yaml.dump(public_merged, default_flow_style=False, sort_keys=False)
                secrets_assembled = yaml.dump(secrets_merged, default_flow_style=False, sort_keys=False)
                default_output = Path(".env.yaml")
        else:
            # .env format
            public_parts: list = []
            public_parts.extend(_build_metadata_header(deployments, locals_))
            public_parts.append("")
            for _, p_text, _ in deploy_layers:
                if p_text:
                    public_parts.append(p_text)
            for _, p_text, _ in local_layers:
                if p_text:
                    public_parts.append(p_text)
            public_assembled = "\n".join(public_parts) + "\n"

            secrets_parts: list = []
            for _, _, s_text in deploy_layers:
                if s_text:
                    secrets_parts.append(s_text)
            for _, _, s_text in local_layers:
                if s_text:
                    secrets_parts.append(s_text)

            if embed_files:
                sops_cfg = config_dir / "sops.yaml"
                deploy_dirs = [config_dir / d for d, _, _ in deploy_layers]
                file_lines = _embed_files_section(embed_files, deploy_dirs, sops_cfg)
                if file_lines:
                    secrets_parts.append("#@dotconfig: files")
                    secrets_parts.extend(file_lines)

            secrets_assembled = "\n".join(secrets_parts) + "\n" if secrets_parts else ""

            default_output = Path(".env")

            if no_export:
                public_assembled = _strip_export_prefix(public_assembled)
                secrets_assembled = _strip_export_prefix(secrets_assembled)

        dest = output if output else default_output
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(public_assembled)
        ok(f"Written to {dest}")

        if secrets_assembled.strip():
            secret_dest = _split_path(dest)
            secret_dest.write_text(secrets_assembled)
            ok(f"Written to {secret_dest}")

    elif fmt in ("json", "yaml"):
        # ---- Structured output ----
        # Single-layer only — CLI rejects multi-layer + structured combo.
        public_dict = _env_lines_to_dict(public_text)
        secrets_dict = _env_lines_to_dict(secrets_text)
        local_public_dict = _env_lines_to_dict(local_public_text)
        local_secrets_dict = _env_lines_to_dict(local_secrets_text)

        if flat:
            result: Any = {}
            result.update(public_dict)
            result.update(secrets_dict)
            result.update(local_public_dict)
            result.update(local_secrets_dict)
        else:
            result = {
                "_dotconfig": {"deploy": deployment_first},
                deployment_first: {
                    "public": public_dict,
                    "secrets": secrets_dict,
                },
            }
            if local_first:
                result["_dotconfig"]["local"] = local_first
                result[local_first] = {
                    "public": local_public_dict,
                    "secrets": local_secrets_dict,
                }

        if fmt == "json":
            assembled = json.dumps(result, indent=2) + "\n"
            default_output = Path(".env.json")
        else:
            assembled = yaml.dump(result, default_flow_style=False, sort_keys=False)
            default_output = Path(".env.yaml")

        if to_stdout:
            click.echo(assembled, nl=False)
        else:
            dest = output if output else default_output
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(assembled)
            ok(f"Written to {dest}")
    else:
        # ---- Classic .env output (multi-layer aware) ----
        parts: list = []
        parts.extend(_build_metadata_header(deployments, locals_))
        parts.append("")

        for d_name, p_text, s_text in deploy_layers:
            parts.append(f"#@dotconfig: public ({d_name})")
            if p_text:
                parts.append(p_text)
            parts.append("")
            parts.append(f"#@dotconfig: secrets ({d_name})")
            if s_text:
                parts.append(s_text)
            parts.append("")

        for l_name, p_text, s_text in local_layers:
            parts.append(f"#@dotconfig: public-local ({l_name})")
            if p_text:
                parts.append(p_text)
            parts.append("")
            parts.append(f"#@dotconfig: secrets-local ({l_name})")
            if s_text:
                parts.append(s_text)
            parts.append("")

        if embed_files:
            sops_cfg = config_dir / "sops.yaml"
            deploy_dirs = [config_dir / d for d, _, _ in deploy_layers]
            file_lines = _embed_files_section(embed_files, deploy_dirs, sops_cfg)
            if file_lines:
                parts.append("#@dotconfig: files")
                for line in file_lines:
                    parts.append(line)
                parts.append("")

        # The legacy single-layer writer ended without a trailing blank
        # line block, so trim one trailing empty element to keep
        # byte-for-byte parity with previous releases.
        if parts and parts[-1] == "":
            parts.pop()

        assembled = "\n".join(parts) + "\n"
        if no_export:
            assembled = _strip_export_prefix(assembled)
        default_output = Path(".env")

        if to_stdout:
            click.echo(assembled, nl=False)
        else:
            dest = output if output else default_output
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(assembled)
            ok(f"Written to {dest}")


def _build_metadata_header(deployments: list, locals_: list) -> list:
    """Build the ``# CONFIG_DEPLOY[S]=`` / ``# CONFIG_LOCAL[S]=`` header lines.

    Single-layer cases use the legacy singular keys (preserves byte-for-byte
    parity with previous releases for tests/fixtures); multi-layer cases use
    the new comma-separated plural keys.
    """
    lines: list = []
    if len(deployments) == 1:
        lines.append(f"# CONFIG_DEPLOY={deployments[0]}")
    elif len(deployments) > 1:
        lines.append(f"# CONFIG_DEPLOYS={','.join(deployments)}")
    if len(locals_) == 1:
        lines.append(f"# CONFIG_LOCAL={locals_[0]}")
    elif len(locals_) > 1:
        lines.append(f"# CONFIG_LOCALS={','.join(locals_)}")
    return lines
